### ISSUE TITLE
Bias naming inconsistencies 

### ISSUE THREAD

**Issue by lbednarczyk** [EducationShinyAppTeam/Survey_Bias#7]
In the explore tab, two of the types of biases are defined as Unnecessarily Complex: Double-barreled and Unnecessarily Complex: Double Negatives. However, in the game there is one combined answer choice that corresponds to these types of biases that is called "unnecessary", which is confusing.

**Comment by neilhatfield** [comment]
We're going to see if the wording changes in https://github.com/EducationShinyAppTeam/Survey_Bias/commit/4c6fbf5ef318895abf4462333dc55d6fffd039e8 help to resolve this issue.

**Comment by neilhatfield** [comment]
I believe this is now resolved.
