### ISSUE TITLE
layout idea

### ISSUE THREAD

**Issue by kqp5476** [EducationShinyAppTeam/Survey_Bias#8]
Masonry layout might look nice so that the large, white gaps are filled-in when the user only has 1 pull-down in use

![Screen Shot 2021-05-18 at 9 24 04 PM](https://user-images.githubusercontent.com/65611715/118742943-60a73580-b81f-11eb-83f2-f85468fe008a.png)

**Comment by neilhatfield** [comment]
An interesting idea. At this time I don't think that we'll move forward with this. The current gaps are a result of boxes not being expanded.
